<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AeroTech.Ordering.Persistence\AeroTech.Ordering.Persistence.csproj" />
    <ProjectReference Include="..\AeroTech.Ordering.Providers\AeroTech.Ordering.Providers.csproj" />
    <ProjectReference Include="..\AeroTech.Ordering.Query\AeroTech.Ordering.Query.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
